### ISSUE TITLE
Weekly progress line fill

### ISSUE THREAD

**Issue by pjw6193** [pjw6193/caliber#613]
### Issue Description
On the VP/QC home, the Weekly Progress line chart is supposed to have only lines without the default fill underneath. Mostly this works but some threshold seems to snap the Chart.js and cause new lines to have the fill.

### Expected behavior
No fill under any of the lines

### Actual behavior (bugs)
Fill under line 'n+1' 
### Steps for replicating (bugs)
Create many current batches with weekly Trainer assessments/grades

### Screenshots (if applicable)
![weekly-progress-fill](https://user-images.githubusercontent.com/20826349/28855743-9ed93f36-770c-11e7-9fd2-4045d8c6424e.png)
(names are hidden to protect the innocent)

**Comment by DanJ1** [comment]
The issue was solved.
