### ISSUE TITLE
QC statuses out of order

### ISSUE THREAD

**Issue by pjw6193** [pjw6193/caliber#648]
### Issue Description
The stacked bar graph on the QC/VP home should be the legend and table in descending order: Superstar, Good, Average, Poor. This will make the report more readable

### Screenshots (if applicable)
![qc](https://user-images.githubusercontent.com/20826349/29681473-bd75faa8-88d5-11e7-9f94-3fdae499ed74.png)

**Comment by ForSerious** [comment]
Done and done.
