### ISSUE TITLE
Multi-trainee tech skills chart showing same colors

### ISSUE THREAD

**Issue by pburns96** [pjw6193/caliber#676]
### Issue Description
When reporting on Batch Overall, we have an option to select more than 1 trainee to compare against the batch and other trainees on the Technical Skills chart.However, sometimes when you select another trainee, they get an already repeated color on the chart.

### Expected behavior
There should be reasonable differentiation between the colors on this report. Possibly the graph should only use unique colors.

### Actual behavior (bugs)
Trainee color repeats a previous color
### Steps for replicating (bugs)
Add many trainees to radar chart and randomly get two with the same/similar color. Refresh the page to get new colors.
### Screenshots (if applicable)
![capture](https://user-images.githubusercontent.com/20909225/30454845-bbf86444-996b-11e7-8f69-995c3f5ba700.PNG)

**Comment by pjw6193** [comment]
resolved
