### ISSUE TITLE
 Single week batch disproportionately affecting batch average.

### ISSUE THREAD

**Issue by WilliamRLewis** [pjw6193/caliber#677]
### Issue Description
Currently when one makes a new batch with assessments only for the first week the company benchmark for cumulative scores bar graph is dramatically dropped. Adding additional weeks with assessments produces the expected average result. 

### Expected behavior
Company average benchmark rises slightly with an above average week 1 assessment, and lowers slightly with a below average week 1 assessment. 
### Actual behavior (bugs)
When only week one is assessed, company average drops dramatically, regardless of how the batch performed. When a second week is added and assessed program behaves normally.
### Steps for replicating (bugs)
To replicate: As a VP, create a new batch, add some trainees and an assessment for their first week. Note even if they are all given high marks the company benchmark drops dramatically.

**Comment by pjw6193** [comment]
this issue may be a miscalculation of the company average. definitely high priority issue!

**Comment by pjw6193** [comment]
closed
