### ISSUE TITLE
Update email for Trainee

### ISSUE THREAD

**Issue by BenNoonan** [pjw6193/caliber#681]
### Issue Description
When a Trainer tries to either update or add a new trainee Email to a batch, a message that an existing email prevents any changes. If the email is left unchanged then the trainee can be updated.
### Expected behavior
Adding or changing a new email to a trainee updates the email for that trainee.
### Actual behavior (bugs)
When adding or changing a new email to a trainee displays the modal message, "The email specified already exists.".
### Steps for replicating (bugs)
As a Trainer, go to Mange Batch tab, select the View/Add Trainees, edit any existing Trainees and change their email. 
### Screenshots (if applicable)
![trainee_email](https://user-images.githubusercontent.com/8796821/30487482-9f684ab0-9a01-11e7-9eda-657e429cb466.png)

**Comment by pjw6193** [comment]
resolved
