### ISSUE TITLE
Unable to update Trainer's email

### ISSUE THREAD

**Issue by BenNoonan** [pjw6193/caliber#727]
![bug_email](https://user-images.githubusercontent.com/8796821/30869234-9ec53d1a-a2ae-11e7-986a-41ef6d359358.png)
### Background/Context
Trying to update a trainer's email will not be updated in the database.
### Expected behavior
Changing a trainer's email, will update the email.
### Actual behavior (bugs)
Changing a trainer's email will not change the email
### Steps for replicating (bugs)
Going to the Trainers tab under 'Settings', select any Trainer/QC/VP, edit their profile, and then update there email.
### Screenshots (if applicable)

**Comment by pjw6193** [comment]
PR #732 resolved
