### ISSUE TITLE
Assessment Update doesn't properly work on the Assess page

### ISSUE THREAD

**Issue by LordFratz** [pjw6193/caliber#739]
### Issue Description
Updating Assessments on the Asses Batch page doesn't properly update the database. Additionally, upon pressing the Update button, all other assessments in the week are populated with the changed info. Whether multiple assessments will change once publish to database is fixed is worth looking into.

### Expected behavior
Pressing the Update button will change the database for that assessment only and will properly populate the values on the web page to reflect the change.

### Actual behavior (bugs)
Pressing the Update button doesn't change the database and it populates other assessments within the same week with the data that was updated, this means they aren't displaying their data.

### Steps for replicating (bugs)
Update a Assessment with changed values. Make sure the containing week has multiple assessments to test the 2nd unwanted behavior.

**Comment by pjw6193** [comment]
resolved
